# Site settings
title: Happy Collision
email: don@happycollision.com
description: > # this means to ignore newlines until "baseurl:"
  I am happy to help with many a digital-world need. It was nice to run into you today.
twitter_username: happycollision
github_username:  happycollision

baseurl: "/jekyll.happycollision.com" # the subpath of your site, e.g. /blog/
url: "http://happycollision.github.io" # the base hostname & protocol for your site

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ['smart']

permalink: pretty

exclude:
  - .bowerrc
  - .gitignore
  - bower.json
  