export const shows = [
  {
    name: "St. Patrick's 2023",
    slug: "2023-03",
    sets: [
      [
        { song: "boys-are-back", feat: "WP" },
        { song: "drink-the-night-away", feat: "WP" },
        { song: "bvb", feat: "WP" },
        { song: "paddy-murphy-died", feat: "WP" },
        { song: "father-mallorys-dance", feat: "Don" },
        { song: "nelsons-blood", feat: "Don" },
        { song: "fightin-nolan", feat: "WP" },
        { song: "kiss-me-im-irish", feat: "WP" },
        { song: "peggy-gordon", feat: "Nick" },
        { song: "dirty-old-town", feat: "WP" },
        { song: "irish-rover", feat: "WP" },
        { song: "spanish-lady", feat: "Don" },
        { song: "rattlin-bog", feat: "Adam" },
        { song: "galway-girl", feat: "Nick" },
        { song: "wild-rover", feat: "WP" },
      ],
      [
        { song: "drunken-sailor", feat: "WP" },
        { song: "paddy-on-the-railway", feat: "WP" },
        { song: "big-strong-man", feat: "Adam" },
        { song: "molly-malone", feat: "WP" },
        { song: "oh-maggie", feat: "Nick" },
        { song: "come-my-friends", feat: "Don" },
        { song: "son-never-shines", feat: "Don" },
        { song: "danny-boy", feat: "Don" },
        { song: "caledonia", feat: "Don" },
        { song: "road-to-ruin", feat: "WP" },
        { song: "jack-dolan", feat: "WP" },
        { song: "new-york-girls", feat: "WP" },
        { song: "mary-mac", feat: "Adam" },
      ],
      [
        { song: "nancy-whiskey", feat: "WP" },
        { song: "star-of-the-county-down", feat: "Don" },
        { song: "rosie", feat: "WP" },
        { song: "tell-me-ma", feat: "WP" },
        { song: "black-and-tans", feat: "WP" },
        { song: "wagon-wheel", feat: "Don" },
        { song: "jock-stuart", feat: "WP" },
        { song: "go-lassie-go", feat: "Nick" },
        { song: "water-is-wide", feat: "Don" },
        { song: "mike-dempsey", feat: "WP" },
        { song: "scotsman", feat: "Adam" },
        { song: "whiskey-in-the-world", feat: "WP" },
        { song: "queen-of-argyll", feat: "WP" },
        { song: "whiskey-in-the-jar", feat: "WP" },
      ],
    ],
  },
]
